bmpLogo:   	insert_bitmap2 "resources/logo.bmp",  128, 37

bmpCursor:  	insert_bitmap2t "resources/cursor.bmp",  16, 16

bmpF:    	insert_bitmap2 "resources/f.bmp", 16, 16
bmpQ:    	insert_bitmap2 "resources/q.bmp", 16, 16

bmpB:    	insert_bitmap2 "resources/b.bmp",  16, 16

bmpUn:   	insert_bitmap2 "resources/un.bmp", 16, 16
bmp0:    	insert_bitmap2 "resources/0.bmp",  16, 16
bmp1:    	insert_bitmap2 "resources/1.bmp",  16, 16
bmp2:    	insert_bitmap2 "resources/2.bmp",  16, 16
bmp3:    	insert_bitmap2 "resources/3.bmp",  16, 16
bmp4:    	insert_bitmap2 "resources/4.bmp",  16, 16
bmp5:    	insert_bitmap2 "resources/5.bmp",  16, 16
bmp6:    	insert_bitmap2 "resources/6.bmp",  16, 16
bmp7:    	insert_bitmap2 "resources/7.bmp",  16, 16
bmp8:    	insert_bitmap2 "resources/8.bmp",  16, 16

bmpGood: 	insert_bitmap2 "resources/good.bmp", 24, 24
bmpBad:  	insert_bitmap2 "resources/bad.bmp", 24, 24
bmpWin:  	insert_bitmap2 "resources/win.bmp", 24, 24

bmpN0:   	insert_bitmap2 "resources/n0.bmp", 12, 21
bmpN1:   	insert_bitmap2 "resources/n1.bmp", 12, 21
bmpN2:   	insert_bitmap2 "resources/n2.bmp", 12, 21
bmpN3:   	insert_bitmap2 "resources/n3.bmp", 12, 21
bmpN4:   	insert_bitmap2 "resources/n4.bmp", 12, 21
bmpN5:   	insert_bitmap2 "resources/n5.bmp", 12, 21
bmpN6:   	insert_bitmap2 "resources/n6.bmp", 12, 21
bmpN7:   	insert_bitmap2 "resources/n7.bmp", 12, 21
bmpN8:   	insert_bitmap2 "resources/n8.bmp", 12, 21
bmpN9:   	insert_bitmap2 "resources/n9.bmp", 12, 21                          

bmpBlock:   	insert_bitmap2 "resources/block.bmp", 16, 16                       

